version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db
  app:
    container_name: php812
    image: ${SYS_USER}/php81
    build:
      context: ./php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 2400:80
    volumes:
      - type: bind
        source: ./source
        target: /var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db