version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: dahas
      MYSQL_PASSWORD: bavaria
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  site:
    container_name: php82
    image: dahas68/php82
    build:
      context: ./
    ports:
      - 8000:80
    depends_on:
      - db
volumes:
  db_data: